# 서버 설정
server:
  shutdown: graceful
  port: ${PORT:8088}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
#  error:
#    path: /error
#    include-exception: true
#    include-stacktrace: always
#    whitelabel:
#      enabled: false
  servlet:
    session:
      timeout: 30m

spring:
  config:
    activate:
      on-profile: common

  # DataSource 설정
  datasource:
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED

  #JPA 설정.
  jpa:
    open-in-view: false
    properties:
      hibernate: # Hibernate - Optimizing
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate



  # 정적리소스
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-location: classpath:/static
      add-mappings: true

  # Jackson - json pretty
  jackson:
    serialization:
      indent_output: true

  session:
    redis:
      flush-mode: ON_SAVE
      namespace: spring:session:flex
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password: ''

#  error:
#    path: /error/404


# 중요 정보 암호화
jasypt:
  encryptor:
    bean: encryptorBean

# actuator 설정
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,beans,conditions
        exclude: threaddump, heapdump
  endpoint:
    info:
      show-details: always
    health:
      show-details: always

#
mybatis:
  type-aliases-package:  me.univ.flex
  mapper-locations: mapper/*.xml