spring:
  config:
    activate:
      on-profile: setup-local
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

flex:
  applicationName: 'Flex'
  security-props:
    password-encoder: 'SHA-256'
    key:
      aes-256: cRBEboDiI6BWJElDVzswipbBJNJBivSD